// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteBookKeeper.Api.Db;

#nullable disable

namespace NoteBookKeeper.Api.Migrations
{
    [DbContext(typeof(NoteKeeperContext))]
    partial class NoteKeeperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NoteSettingId")
                        .HasColumnType("int");

                    b.Property<string>("RedirectLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NoteSettingId");

                    b.ToTable("NoteItems");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteItemFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NoteItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NoteItemId");

                    b.ToTable("NoteItemsFiles");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NoteSettings");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteItem", b =>
                {
                    b.HasOne("NoteBookKeeper.Api.Entities.NoteSetting", "NoteSetting")
                        .WithMany("Items")
                        .HasForeignKey("NoteSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NoteSetting");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteItemFile", b =>
                {
                    b.HasOne("NoteBookKeeper.Api.Entities.NoteItem", "NoteItem")
                        .WithMany("Files")
                        .HasForeignKey("NoteItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NoteItem");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteSetting", b =>
                {
                    b.HasOne("NoteBookKeeper.Api.Entities.User", "User")
                        .WithMany("NoteSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteItem", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.NoteSetting", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NoteBookKeeper.Api.Entities.User", b =>
                {
                    b.Navigation("NoteSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
